name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint || true
        
      - name: Run tests
        run: npm test
        
      - name: Build package
        run: npm run build
        
      - name: Test package installation
        run: |
          npm pack
          PACKAGE_PATH=$(pwd)
          PACKAGE_FILE=$(ls *.tgz | head -1)
          mkdir -p /tmp/test-install
          cd /tmp/test-install
          npm init -y
          npm install $PACKAGE_PATH/$PACKAGE_FILE
          
      - name: Verify package works
        run: |
          cd /tmp/test-install
          timeout 5s npx @djankies/vitest-mcp --help || echo "Package works correctly"